In [2]:
import math

import torch
from sympy import mathml

In [3]:
a = torch.randn(3, 5)
b = torch.randn(5, 2)
c = torch.einsum('ik, kj -> ij', a, b)
c.shape

torch.Size([3, 2])

In [3]:
c.shape

torch.Size([3, 2])

In [4]:
d = a @ b
d

tensor([[ 0.1920, -1.4344],
        [-1.4116,  1.1372],
        [-0.0248, -0.1263]])

In [11]:
a = torch.randn(5)
b = torch.randn(3)
c = torch.einsum('i, j -> ij', a, b)
c.shape

torch.Size([5, 3])

In [7]:
c, c.shape

(tensor([[-1.0260,  1.5687, -0.8067],
         [-1.2430,  1.9004, -0.9773],
         [ 0.5786, -0.8846,  0.4549],
         [ 0.4063, -0.6213,  0.3195],
         [-0.9454,  1.4455, -0.7434]]),
 torch.Size([5, 3]))

In [11]:
d = torch.einsum('ij->i', c)
d, d.shape

(tensor([-0.2640, -0.3198,  0.1489,  0.1046, -0.2433]), torch.Size([5]))

In [12]:
e = torch.randn(3, 4, 5)
f = torch.einsum('ijk->kji', e)
f.shape

torch.Size([5, 4, 3])

In [13]:
a = torch.randn(3, 5)
b = torch.randn(2, 5)
c = torch.einsum('ik, jk -> ij', a, b)
c.shape

torch.Size([3, 2])

In [20]:
a = torch.randn(3, 5)
b = torch.randn(3, 5)
c = torch.einsum('i,i -> ', a[0], b[0])
c.shape

torch.Size([])

In [9]:
a = torch.randn(3, 5, 4)
b = torch.randn(3, 4, 6)
c = torch.einsum('ijk,ikl ->ijl ', a, b)
c.shape

torch.Size([3, 5, 6])

In [8]:
a = torch.tensor(((1, 2, 3), (3, 4, 5)))
b = torch.einsum('i->', a[1])
b

tensor(12)

In [10]:
a = torch.randn(3, 5, 4)
c = torch.einsum('ijk->kji ', a)
c.shape

torch.Size([4, 5, 3])

In [18]:
import math
from torch import nn

In [22]:
q = torch.randn(2, 3, 4, 5) # (bs, nh, sl, dim)
k = torch.randn(2, 3, 4, 5)
v = torch.randn(2, 3, 4, 5)

a = torch.einsum('abcd, abed -> abce', q, k)
print("after matrix multiplication of q & k : ", a.shape)
a /= math.sqrt(5.0)
a = nn.functional.softmax(a, dim=-1)
a = torch.einsum('abcd, abef -> abcf', a, v)
print("after matrix multiplication of atnn & v : ", a.shape)

after matrix multiplication of q & k :  torch.Size([2, 3, 4, 4])
after matrix multiplication of atnn & v :  torch.Size([2, 3, 4, 5])
